### ISSUE TITLE
Elastic APM Monitoring on Courier

### ISSUE THREAD

**Issue by johncordeiro** [nyaruka/courier#357]
How do you guys see the addition of new dependency and env variables to support [Elastic APM](https://www.elastic.co/apm) monitoring on go projects of RapidPro stack like courier and mailroom?

**Comment by nicpottier** [comment]
I'm not super interested in this. I'd like to see mailroom and courier move to using prometheus endpoints instead of librato for metrics as that would scale a lot better. I think this is likely to have similar issues as Librato in that we just generate way too many events under load which is going to get expensive on the logging side. Since Prometheus is pull it dodges that completely and elegantly.
