### ISSUE TITLE
WhatsApp "interactive message" support

### ISSUE THREAD

**Issue by rudigiesler** [nyaruka/courier#360]
The WhatsApp API have added what they call "interactive messages". These are messages that allow users to more easily select an item from a list, with either up to 3 buttons, or a list with up to 10 items.

I think this will fit quite nicely into the "Quick Reply" functionality in RapidPro flows, but there might need to be some hard-coded logic here if we don't want to change the flow editor (eg. 1-3 items = buttons, 3-10 items = list)

I haven't looked into, or tried this functionality yet, but I wanted to get the ball/discussion rolling here so long, to decide if this is something that RapidPro wants to support, and if so, what is the best way to implement it.

Documentation: https://developers.facebook.com/docs/whatsapp/api/messages#interactive-object

**Comment by matmsa27** [comment]
This feature is a good improvement from WhatsApp. The quick reply is a feature long-awaited from our Rapidpro customers. To implement this on Rapidpro, I want to raise two points, that I want to discuss with you.

1 - This feature for interactive messages, is only supported in a version from v2.35.2 WhatsApp API. For this, to use this feature is necessary to have a WhatsApp Docker instance with this version on minimum.
2 - The Whatsapp handler in courier is used to other BSPs, like 360, Textit, and to docker instance. For this, if using a channel like this and the API from WhatsApp doesn't have on the minimum version (v2.35.2), this feature didn't work. And, it doesn't have the minimum version, how courier will treat this? Maybe a solution is to have the version from API on the channel to treat this in a better way when creating flows on Rapidpro to support this? Just ideas and points that I have been thinking about and want to discuss with you.

**Comment by rudigiesler** [comment]
@matmsa27 There have been other features that are only supported on newer versions of the WhatsApp API before, I wonder how those were handled? eg. we started with "highly structured messages" / hsm, then the API moved over to "template messages", which had a different structure.

I'm not 100% sure, but I know that there's a config field on the channel whether to use the hsm/template format in the API.

**Comment by nicpottier** [comment]
Ya, I think adding this definitely makes sense, agree that buttons for quick replies 1-3 and list for more than that.

I guess we'd have to test it out but I bet because `interactive` is a new node in JSON it is just ignored by versions of WhatsApp that don't support it, generally extra JSON works that way. If so, that would make it easy to add for the time being.

If either one of you want to lead adding this, it should be a pretty easy change on the Courier side.

**Comment by johncordeiro** [comment]
hey @nicpottier , I've tried to send in older versions and that's the result:
```
{
    "meta": {
        "version": "v2.33.4",
        "api_status": "stable"
    },
    "errors": [
        {
            "code": 1009,
            "title": "Parameter value is not valid",
            "details": "Parameter 'type' has invalid value 'interactive'"
        }
    ]
}
```
This is because besides the extra JSON the type needs to be "interactive". We're warming up a PR here to send it, let me know just how you guys think is the best approach to check the version before settings up buttons or lists. I agree that needs to be something in the channel, that can be updated over time in some of the sync processes in celery.

**Comment by johncordeiro** [comment]
That sounds good for me, we can handle the PR to rapidpro and courier.

**Comment by rudigiesler** [comment]
@johncordeiro Great to hear :)

Just also keep in mind that Courier will also have to handle the inbound webhook for replies to interactive messages: https://developers.facebook.com/docs/whatsapp/api/webhooks/components#interactive-obj

We can probably do the same logic here as for template buttons, where we take the text of the button/list item, and create an inbound message where the body is the text of the button. See https://github.com/nyaruka/courier/pull/348
